apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: mar20-chatbot-testbuildci
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mar20-chatbot-testbuildci
  name: mar20-chatbot-testbuildci
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi
