apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: mar20-chatbot-testbuildci
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jdubrick-ai/mar20-chatbot-testbuildci:b6a152d382d85ccb390638830d80bcedeab1804c@sha256:e9a65420609eafd166fdb037eb610c37d38cb0275ca01bec64156adbcfa6bc99 # use pre-built to bootstrap
          name: app-inference
